version: "3.8"

services:
  documentserver:
    container_name: documentserver
    image: onlyoffice/documentserver:8.2
    expose:
      - "80"
    environment:
      - JWT_SECRET=4a31760266ac7f3d14c3eaca5bb52851809de9dfa8e90b943d3402febeae82d9

  example:
    container_name: example
    build:
      context: .
      target: example
    expose:
      - "80"
    volumes:
      - "example:/srv"
    environment:
      - ADDRESS=0.0.0.0
      - DOCUMENT_SERVER_PRIVATE_URL=https://bug-free-disco-6rxv7qxjvpqhxq5r-8080.app.github.dev/
      - DOCUMENT_SERVER_PUBLIC_URL=https://bug-free-disco-6rxv7qxjvpqhxq5r-8080.app.github.dev/
      - EXAMPLE_URL=http://proxy
      - JWT_SECRET=4a31760266ac7f3d14c3eaca5bb52851809de9dfa8e90b943d3402febeae82d9
      - PORT=80

  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    depends_on:
      - documentserver
      - example
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "example:/srv"

volumes:
  example:
