<?php
declare(strict_types=1);

namespace App\ActionData;

use Akbarali\ActionData\ActionDataBase;
use App\Models\UserModel;
use Illuminate\Http\UploadedFile;

/**
 * Created by PhpStorm.
 * Filename: UploadFileActionData.php
 * Project Name: uzinfocom-task
 * Author: akbarali
 * Date: 08/02/2025
 * Time: 13:58
 * GitHub: https://github.com/akbarali1
 * Telegram: @akbar_aka
 * E-mail: me@akbarali.uz
 */
class UploadFileActionData extends ActionDataBase
{
	public ?int                  $userId;
	public readonly UploadedFile $file;
	
	protected function prepare(): void
	{
		$this->userId = $this->getUser()->id;
		$this->rules  = [
			"userId" => "required|exists:users,id",
			'file'   => 'required|file|mimes:docm,docx,dotm,dotx,xlsm,xlsx,xltm,xltx,potm,potx,ppsm,ppsx,pptm,pptx,pdf|max:10240',
		];
	}
	
	public function setUser(): void
	{
		$this->user = auth()->user();
	}
	
	public function getUser(): UserModel
	{
		return parent::getUser(); // TODO: Change the autogenerated stub
	}
	
	
}
